CUSTOMER_CARE_REP = 'Customer care rep'
CUSTOMER_CARE_MANAGER = 'Customer care manager'
CUSTOMER_CARE_SUPERVISER = 'Customer care superviser'
TECH_SUPPORT = 'Tech support'
ADMIN = 'Admin'

GROUP_WEIGHTAGE = {
    CUSTOMER_CARE_REP: 100,
    CUSTOMER_CARE_MANAGER : 200,
    CUSTOMER_CARE_SUPERVISER : 300,
    TECH_SUPPORT: 400,
    ADMIN : 999
}


CUSTOMER_CARE_REP_PERMISSIONS = []
CUSTOMER_CARE_MANAGER_PERMISSIONS =  CUSTOMER_CARE_REP_PERMISSIONS + []            
CUSTOMER_CARE_SUPERVISER_PERMISSIONS =  CUSTOMER_CARE_MANAGER_PERMISSIONS + []            
TECH_SUPPORT_PERMISSIONS =  CUSTOMER_CARE_SUPERVISER_PERMISSIONS + []            
ADMIN_PERMISSIONS =  TECH_SUPPORT_PERMISSIONS + []            



GROUPS = [CUSTOMER_CARE_REP, CUSTOMER_CARE_MANAGER, CUSTOMER_CARE_SUPERVISER, TECH_SUPPORT, ADMIN]


GROUP_PERMISSIONS = {
        CUSTOMER_CARE_REP : CUSTOMER_CARE_REP_PERMISSIONS,  # list of tuple > name,code name


        CUSTOMER_CARE_MANAGER: CUSTOMER_CARE_MANAGER_PERMISSIONS,
        CUSTOMER_CARE_SUPERVISER: CUSTOMER_CARE_SUPERVISER_PERMISSIONS,
        TECH_SUPPORT: TECH_SUPPORT_PERMISSIONS,
        ADMIN: ADMIN_PERMISSIONS,
}