# Generated by Django 4.0.7 on 2022-09-23 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('website_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('es', 'Spanish')], default='en', max_length=2)),
                ('communication_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('es', 'Spanish')], default='en', max_length=2)),
                ('force_password_change', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BooleanSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('TWO_FACTOR', 'Enable Two-Factor authentication?'), ('GENERATE_INVOICE', 'Generate invoice for each Transaction?')], max_length=50, verbose_name='Setting')),
                ('value', models.BooleanField(default=False, verbose_name='Enabled')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booleansettings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['user', 'key'],
            },
        ),
        migrations.AddConstraint(
            model_name='booleansettings',
            constraint=models.UniqueConstraint(fields=('user', 'key'), name='User unique Setting'),
        ),
    ]
